#+TITLE: Programming Development Environment Setting Up
#+AUTHOR: Zhengnan Ma(MZN)
#+OPTIONS: toc:2

* Table of Contents :toc:
- [[#arch-linux][Arch Linux]]
  - [[#using-arch-linux][Using Arch Linux]]
  - [[#install-cli-tools-and-apps][Install cli-tools and apps]]
  - [[#configuration][Configuration]]
- [[#macos][Macos]]
  - [[#install-cli-tools-and-apps-1][Install cli-tools and apps]]
  - [[#configuration-1][Configuration]]
- [[#generate-a-install-script][Generate a Install Script]]

* Arch Linux
** Using Arch Linux
*** Install Windows-WSL2

+ i. Search and open the enable or disable Windows features.
+ ii. Open Hyper-V, Virtual Machine Platform and Windows Subsystem for Linux.
+ iii. Open whindows terminal and type:
   #+begin_src sh
   wsl update
   wsl --set-default-version 2
   wsl --list --online
   wsl --install -d ubuntu-24.04,'ubuntu-24.04' could be changed.
 
  #+end_src
+ iv. Open ubuntu terminal and type:
   sudo apt-get update and sudo apt-get upgrade.

Reference:[[https://learn.microsoft.com/zh-cn/windows/wsl/install][Install Linux on Windows with WSL]]

*** Installation (On Windows-WSL2)
+ Download [[https://github.com/yuk7/ArchWSL/releases/tag/25.3.2.0][Arch Linux]] named =Arch.zip=.
+ Double-click =arch.exe=, it will install quickly.
+ Useful commands of =wsl2= Subsystem
  #+begin_src shell
  wsl --list # View the wsl subsystem list
  wsl --unregister Ubuntu # Uninstall Ubuntu subsystem
  wsl --set-default Arch # Set Arch Linux as default.
  wsl -d Arch  # Doesn't need this when last command setted.
  #+end_src

*** Start up
Open =arch= terminal for the first time and configure users .
#+begin_src sh
passwd   # password for root user
echo "%wheel ALL=(ALL) ALL" > /etc/sudoers.d/wheel # sudo
useradd -m -G wheel -s /bin/bash mzn # add none root user
passwd mzn

# Only in wsl2 arch linux
.\Arch.exe config --default-user mzn # Change the default user to a non-root user
#+end_src

*** Pacman
Open arch terminal to complete the configuration.

+ First, configure the pacman mirror source.
#+begin_src sh
vim /etc/pacman.d/mirrorlist
#+end_src
Then add the code below.
#+begin_src sh
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch
#+end_src

+ Pacman-Key 
#+begin_src sh
pacman-key --init
pacman-key --populate
pacman -Sy archlinux-keyring
#+end_src

+ Update Arch Linux.
#+begin_src sh
pacman -Syu
#+end_src

+ Configure the archlinuxcn mirror source.
#+begin_src sh
vim /etc/pacman.conf
#+end_src
Add:
#+begin_src sh
[archlinuxcn]
Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
#+end_src 
+ Install Archlinuxcn key
#+begin_src sh
pacman -Sy archlinuxcn-keyring
#+end_src

*** Refrernce
+ [[https://learn.microsoft.com/en-us/windows/wsl/][Windows Subsystem for Linux Documentation(WSL2)]]
+ [[https://wiki.archlinux.org/title/Main_page][Arch Linux Wiki]]
+ [[https://arch.icekylin.online/][Archlinux Concise Guide]]

*** Search package on arch
[[https://archlinux.org/packages/?sort=&q=&maintainer=&flagged=][Where search the package.]]

** Install cli-tools and apps

This needs to packaging as a script to install these packages automaticlly.
#+begin_src shell
# update packages manager
sudo pacman -Syy # when install failed 
sudo pacman -Syu

# for all programming languages format
sudo pacman -S diffutils

# programming lsp
sudo pacman -S clang
#for c/c++ format
sudo pacman -S clang-format

# cmake
sudo pacman -S make
sudo pacman -S cmake
sudo pacman -S cmake-language-server
# git configuration
sudo pacman -S git 
sudo pacman -S openssh 
# vscode
sudo pacman -S vscode
# emacs and fonts for terminal and emacs
sudo pacman -S emacs
sudo pacman -S ripgrep
sudo pacman -S libvterm
sudo pacman -S ttc-iosevka
sudo pacman -S ttc-iosevka-aile
sudo pacman -S ttf-nerd-fonts-symbols-mono
# only using on wsl2 arch linux to share the clipboard with windows
sudo pacman -S xclip
# terminal and manage the configuration(dotfiles)
sudo pacman -S zsh 
sudo pacman -S stow


#+end_src

*** diffutils
=Diffutils= is a GNU tool set that provides core command-line tools for comparing file and directory differences. Its main function is to generate differences (diff) between files. It is one of the basic tools of Unix/Linux systems. Many development tools (such as =Git=, =Emacs's apheleia=, etc.) rely on it to handle file changes.

1. Tools included in diffutils
   + =diff= compares the differences between two files or directories and outputs the difference lines (used by apheleia for formatting comparison)
   + =cmp= compares two files byte by byte, suitable for binary files
   + =sdiff= displays the differences between two files side by side
   + =diff3= compares the differences between three files (used in merge conflict scenarios)

2. Why does =apheleia= or =git= need diff?
   When apheleia formats code, its default workflow is:
   + Use a formatting tool (such as clang-format) to process the current file and generate a temporary file.
   + Call diff to compare the original file and the temporary file to generate a difference patch.
   + Apply the difference patch to the original file to avoid direct overwriting (to ensure atomicity and safety).

** Configuration
*** Zsh
+ Reference
[[https://wiki.archlinux.org/title/Zsh#Installation][Installation]]
[[https://wiki.archlinux.org/title/Command-line_shell#Changing_your_default_shell][Changing default shell]]

*** Git
+ Configuraiton
#+begin_src sh
git config --global user.name "mzn"  
git config --global user.email "mzn@foxmail.com" 
ssh-keygen -t rsa -C "mzn@foxmail.com"
#+end_src
+ ssh
#+begin_src sh
~/.ssh/id_rsa.pub copy to https://github.com/settings/ssh/new 

ssh -T git@github.com # verified if it is configure successful

sudo pacman -S openssh # if varified failed

#+end_src
+ Reference
 [[https://qiuyedx.com/?p=1852][Blog]]
 [[https://superuser.com/questions/335534/ssh-keygen-command-not-found-when-setting-up-git-on-windows][ssh varified failed]]

* Macos
** Install cli-tools and apps
First of all, I need to install [[https://brew.sh/][brew]].
- Update and Upgrade
#+begin_src shell
brew update 
brew upgrade
#+end_src

- CLI tools
#+begin_src shell

brew install fzf
brew install fd
brew install ripgrep 
brew install git
brew install lazygit
brew install stow
brew install tree

#+end_src

- App
#+begin_src shell

brew install --cask emacs
brew install --cask google-chrome
brew install --cask wezterm
brew install --cask visual-studio-code
brew install --cask font-iosevka
brew install --cask wechat

#+end_src

** Configuration
Others are the same as Arch Linux.

* Generate a Install Script
